allowed-worlds: []
statistic: false


# Time in seconds before a conversation is automatically canceled
conversation-timeout: 120

# Words that cancel a conversation
conversation-cancel-words:
  - "cancel"
  - "annuler"
  - "stop"
  - "quit"

# List of blocked colors
blocked-colors:
  - "&4"
  - "&c"
  - "&k"