allowed-worlds: []
statistic: false


# Time in seconds before a conversation is automatically canceled
conversation-timeout: 120

# Words that cancel a conversation
conversation-cancel-words:
  - "cancel"
  - "annuler"
  - "stop"
  - "quit"

# List of blocked colors
blocked-colors:
  - "&4"
  - "&c"
  - "&k"

default-value:
  state:
    # Uncomment the next line to set the default value of the set flag to ALLOW
    # use: true
  string:
    # Uncomment the next line to set the default value of the greeting flag"
    # greeting: "&6Welcome to the land of &a%player%"